default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo1_development
  host: localhost
  port: 5430
  username: postgres
  password: cicasia32

test:
  <<: *default
  database: demo1_test
  host: localhost
  port: 5430
  username: postgres
  password: cicasia32

production:
  <<: *default
  database: demo1_production
  username: demo1
  password: <%= ENV["DEMO1_DATABASE_PASSWORD"] %>